version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: cci_postgres
    environment:
      POSTGRES_USER: cci_user
      POSTGRES_PASSWORD: cci_pass
      POSTGRES_DB: cci_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
